# Generated by Django 4.0.6 on 2022-07-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_useraccount_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='images'),
        ),
    ]
