# Generated by Django 4.0.6 on 2022-07-25 04:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContestParticipant',
            new_name='ParticipantContest',
        ),
    ]
