# Generated by Django 4.0.6 on 2022-08-01 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0002_rename_contestparticipant_participantcontest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContestRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='prize',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='WeeklyScore',
        ),
        migrations.AddField(
            model_name='contestrules',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contest.contest'),
        ),
        migrations.AddField(
            model_name='contestrules',
            name='score_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.scoremethod'),
        ),
        migrations.AddField(
            model_name='contestround',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contest.contest'),
        ),
        migrations.AddField(
            model_name='contestround',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
