name: Deploy to Production
on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  VPS_HOST: ${{ secrets.VPS_HOST }}
  VPS_USER: ${{ secrets.VPS_USER }}
  SITE_NAME: contests
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
      - name: Add SSH host to known_hosts
        run: ssh-keyscan ${{ env.VPS_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy
        run: |
          ssh ${{ env.VPS_USER }}@${{ env.VPS_HOST }} bash -i  << 'EOF'
            cd ~/apps/${{ env.SITE_NAME }}
            git pull origin main
            pipenv install --deploy
            pipenv run python manage.py migrate --noinput
            pipenv run python manage.py collectstatic --noinput
            sudo systemctl restart ${{ env.SITE_NAME }}.gunicorn
          EOF
      - name: Deployment summary
        run: |
          echo "🚀 Deployed to ${{ env.VPS_HOST }}"
          echo "📁 Site: ${{ env.SITE_NAME }}"